### ISSUE TITLE
Using VTooltip Component Not Working

### ISSUE THREAD

**Issue by wendybujalski** [Akryum/floating-vue#1020]
Using VTooltip according to the documentation gives me this error -

![Screenshot 2024-01-26 at 1 36 49 PM](https://github.com/Akryum/floating-vue/assets/8495209/71c46200-fe61-4490-b75b-2102f6b6a5cd)

I've reproduced the issue here -

https://stackblitz.com/edit/vitejs-vite-9kmmmt?file=src%2FApp.vue

**Comment by Akryum** [comment]
Your import is wrong, it should be `import { vTooltip } from 'floating-vue'`

**Comment by wendybujalski** [comment]
I've updated the import to be `import { vTooltip } from 'floating-vue'` and still appear to have the same problem.
