### ISSUE TITLE
Re-focusing the trigger, when closing via `esc` key

### ISSUE THREAD

**Issue by dobromir-hristov** [Akryum/floating-vue#1021]
Ideally for AX, the focus should go back to the trigger button when you close a dropdown via the `esc` key.

I tried capturing the `esc` keydown event in the `popper` slot, but that only works if I am focused on an item, inside the slot itself, not the outer `v-popper__popper`, which is focused when you open the dropdown for example. 

If the `hide` event would specify the reason for closing, we could do the re-focusing on our end.

**Comment by Akryum** [comment]
What would be the use case for an additional parameter to `hide`? Doesn't it work if you just listen to `hide` and focus your button?

**Comment by dobromir-hristov** [comment]
That will focus if you click outside, or hide via some other mechanism, which is probably not correct 🤔 not exactly sure what is more correct, from an accessibility standpoint.

**Comment by Akryum** [comment]
Maybe you can do something similar to:

```
function onHide () {
  if (document.activeElement === document.body) {
    myButton.value.focus()
  }
}
```

**Comment by dobromir-hristov** [comment]
Right, that did the trick :)

```js
 const activeEl = document.activeElement
  if (!activeEl || activeEl === document.body || activeEl.classList.contains('v-popper__popper')) {
    // focus the trigger button
  }
```
