### ISSUE TITLE
Tooltip position is affected by developer tools (chrome)

### ISSUE THREAD

**Issue by nothingrandom** [Akryum/floating-vue#186]
If developer tools are open on Chrome then the position of the tooltip is affected, with it showing the height of the developer tools above the correct position.

It appears from further investigation this is when the page without the dev tools console wouldn't need scroll but with the addition / opening of it, it does then need to scroll.

**Comment by Akryum** [comment]
I'm not sure this is fixable nor relevant, since it should only affect the developer of the app.
