### ISSUE TITLE
The component's events or classes overrides the v-tooltip class and events

### ISSUE THREAD

**Issue by karolinakuzniewicz** [Akryum/floating-vue#261]
If the component has v-tooltip directive, bind my personal classes and specified the functions on component's events `@mouseenter` and `@mouseleave`, the tooltip is not working properly. The tooltip show up on certain items but doesn't hide after the mouse is no longer focusing on the component. It is related to these events defined on the component, without them everything works as expected and fine. I've found that if the component has own classes (bound with Object-style notation in my case) the v-tooltip class ` has-tooltip` is not added to the component but without it the tooltip shows up. 

Can it be fixed somehow? The component I'm using needs to have `v-tooltip` and `@mouseenter` and `@mouseleave` defined.

**Comment by Akryum** [comment]
Please provide a runnable reproduction, thanks!
