### ISSUE TITLE
Duplicate events when using open.sync

### ISSUE THREAD

**Issue by pvlcor** [Akryum/floating-vue#376]
**Current behaviour:** 
- When using .sync on open prop, VPopover emits 2 times **hide/show** and **update** events
![image](https://user-images.githubusercontent.com/11644634/67202228-c8618880-f410-11e9-89c2-67f8b60fe888.png)

**Expected behaviour:** 
- **hide/show** and **update** events are emitted only once

**Comment by laurensiusadi** [comment]
Why is the popover component emitting `hide` event when it's not opened yet?

**Comment by jkohlin** [comment]
I have a similar issue, v-popover emits _update:open(false)_ twice when I close the popover by clicking on my popover-button
```
…
<v-popover
  @update:open="callForBenchmark"
>
  <button>Benchmark</button>
  <dropdown-benchmarks
    ref="benchmark"
    slot="popover"
    :card="card"
    @update:benchmark="saveBenchmark"
  />
</v-popover>
</template>
<script>
…
methods:{
  callForBenchmark(open) {
    console.log(`callForBenchmark.open: ${open}`);
    if (!open && this.$refs.benchmark) {
      this.$refs.benchmark.saveBenchmark();
    }
  },
  saveBenchmark(payload) {
    this.card.save()
  },
}
```

In DropdownBenchmark:
````
saveBenchmark() {
      this.$emit('update:benchmark',this.benchmarks),
    },
```

**Comment by Lanuitjedanse** [comment]
I also have this issue (all hide and show events are duplicated), do you plan on fixing it soon? 
Or do you have a recommended solution?

**Comment by dev-steverob** [comment]
I had similar issue when using hover menu and I got around it by doing debounce on the function to only trigger after 300ms if different from the previous state and this stopped the duplicate calls
