### ISSUE TITLE
Not support Nuxt 3

### ISSUE THREAD

**Issue by dungonfq** [Akryum/floating-vue#820]
Hi,

I acted upon ur introduction to install `floating-vue` into Nuxt 3: https://v-tooltip.netlify.app/guide/installation.html#nuxt-3

1. But when run 'nuxi dev', it fired the error:
<img width="577" alt="Screen Shot 2022-01-19 at 5 12 47 PM" src="https://user-images.githubusercontent.com/57652048/150110080-734fa26f-2ff1-40de-b246-014298c077f0.png">

2. If I run 'nuxi build' then 'nuxi start', the error was shown:
<img width="1100" alt="Screen Shot 2022-01-19 at 5 14 20 PM" src="https://user-images.githubusercontent.com/57652048/150110418-73064497-71bf-45b1-a652-c779126e4efe.png">

- It violate the new rules of Native ES module https://v3.nuxtjs.org/concepts/esm

Please help to take a look. Thank u

**Comment by serhez** [comment]
Getting the same errors.

**Comment by mgnrfk** [comment]
Same here!

**Comment by antfu** [comment]
It looks like `floating-vue/nuxt` module is missing. Before it been shipped, the workaround is to create `plugins/floating-vue.ts` with following content:

```ts
import { defineNuxtPlugin } from '#app'
import FloatingVue from 'floating-vue'
import 'floating-vue/dist/style.css'

export default defineNuxtPlugin(({ vueApp }) => {
  vueApp.use(FloatingVue)
})
```

**Comment by andyjamesn** [comment]
I am unable to get this to work in Nuxt3. Following the documentation for Nuxt3 

https://floating-vue.starpad.dev/guide/installation.html#nuxt-3

Just added 'floating-vue/nuxt', to buildModules

I do not get any errors but also when I add v-tooltip="text" it is not rendering any tooltips.

Andy ideas?

**Comment by Akryum** [comment]
I just tried with the latest version and I have no issue

**Comment by andyjamesn** [comment]
I installed using 

`npm i -S floating-vue`

As per the docs, it shows this is the version installed

"floating-vue": "^2.0.0-beta.7"

Nuxt is 

"nuxt3": "latest",

Is there any additional setup required like importing the css? or is it just adding 'floating-vue/nuxt' tio nuxtConfig?

**Comment by Akryum** [comment]
Yes

**Comment by andyjamesn** [comment]
Thanks for your help. I cleared node_modules and ran npm install and it is working now

**Comment by romain-ortega** [comment]
Hello @Akryum,
I have striclty followed the current documentation using : 
- `floating-vue: ^2.0.0-beta.15`
- `nuxt3: latest`

I have added this expected code in my nuxt.config.ts :
```ts
import { defineNuxtConfig } from 'nuxt3'

export default defineNuxtConfig({
  buildModules: [
    'floating-vue/nuxt',
  ],
})
```

But I got the following error :
`Cannot find module 'floating-vue/nuxt'`

By following @antfu workaround, I got it working locally, in dev mode (needed to also remove code sample above).

**However**, when building for production, I'm stuck with this error : 
`Cannot destructure property 'popperId' of 'undefined' as it is undefined.`

Did I missing something ?

**Comment by sewalsh** [comment]
The `nuxt.mjs` file is missing from the published NPM package (check your `node_modules/floating-vue` dir) which is causing the error when you add it to the buildModules array. `buildModules: ['floating-vue/nuxt' ]` 

If you manually add the [nuxt.mjs](https://github.com/Akryum/floating-vue/blob/main/packages/floating-vue/nuxt.mjs) file, it works.

Perhaps this package build pipeline is filtering out the `nuxt.mjs` file?

**Comment by jonorozcoc** [comment]
You have to add it to `modules ` instead of `buildModules`
