### ISSUE TITLE
Module parse failed: Unexpected token You may need an appropriate loader to handle this file type

### ISSUE THREAD

**Issue by mkhalid03** [Akryum/floating-vue#826]
Hi

I tried installing `floating-vue`  using `npm i -S floating-vue@vue2`

Then added  these lines to `main.js` file
```
import FloatingVue from 'floating-vue'
Vue.use(FloatingVue)
```

After running `npm run dev` I am getting following error

<img width="1129" alt="Screenshot 2022-02-12 at 3 32 15 PM" src="https://user-images.githubusercontent.com/8999960/153707938-f2584b2b-03cf-4d99-943e-00546044fb8c.png">

Please help to take a look. Thank u

**Comment by Akryum** [comment]
Your babel configuration is probably incorrect.

**Comment by mkhalid03** [comment]
For a VUE 2 project generated through VUE CLI fixed the issue by adding 

```
{
    test: /@?(floating-ui).*\.(ts|js)x?$/,
    loader: 'babel-loader'
}
```

under **rules** section in file `webpack.base.conf.js`
