### ISSUE TITLE
Skip position calculation on scroll if tooltip is not displayed

### ISSUE THREAD

**Issue by ladariha** [Akryum/floating-vue#835]
I have a long list of items (~1000), each item has let's say <10 tooltips made with `v-tooltip`:

```typescript
app.use(FloatingVue, {
            themes: {
                "info-tooltip": {
                    placement: "top",
                    $extend: "tooltip",
                    distance: 5,
                    delay: { show: 800, hide: 0 },
                }
            },
        });
```

and then used like
```html
<span v-tooltip="{ theme: 'info-tooltip', content: 'Some label here' }">
```
When having hundreds of such tootltips, there is a performance issue when scrolling over the list of 1000 items as the scroll appears to be calling `$_computePosition` (even if no titles/tooltips are displayed to user) from Popper.ts from this code:

```typescript
// Scroll
      if (!this.positioningDisabled) {
        addListeners([
          ...getScrollParents(this.$_referenceNode),
          ...getScrollParents(this.$_popperNode),
        ], 'scroll', () => {
          this.$_computePosition()
        })
      }
```

I guess I understand why it is needed, but would it be possible to either:
- add ability to skip `_computePosition` on scroll via props
- or maybe even better, do not calculate position if tooltip is not displayed?

I've noticed in the `$_computePosition` there is following condition:
```typescript
    async $_computePosition () {
      if (this.$_isDisposed || this.positioningDisabled) return
```

but in my case, the `this.$_isDisposed` is `false` so it won't bail out from the method. Not sure if the `false` is correct or not

**Comment by ladariha** [comment]
Here's a [reproducible case](https://codesandbox.io/s/modern-browser-6ckx7r?file=/src/main.js) . You can see the scrolling is laggy but if you uncomment 
```javascript
// positioningDisabled: true,
```
inside `main.js`, the performance is much better

**Comment by ladariha** [comment]
@Akryum Thanks a lot for quick fix. May I ask if you have some ETA regarding publishing it to NPM registry?

**Comment by Akryum** [comment]
It is now deployed
