### ISSUE TITLE
[Severity] Showing black border after page refreshed

### ISSUE THREAD

**Issue by Paper-Folding** [Akryum/floating-vue#848]
Here I write a quick code sandbox for this issue(the link provided below might sometimes got unstable and show you an import module error, just refresh the page should be ok), can anyone pls help me:  
https://codesandbox.io/s/floating-vue-black-border-ofd718?file=/src/App.vue

Normal state
![image](https://user-images.githubusercontent.com/49343539/161431307-6e3b9279-27ac-4d7b-a0cb-7547122aa5f1.png)

After page refreshed:
![image](https://user-images.githubusercontent.com/49343539/161431263-3c57718c-cd24-459e-b00c-74cfe7a49396.png)

My code(simplified)
```html
<template>
    <VMenu
        strategy="fixed"
        :triggers="['focus']"
        :showTriggers="triggers => [...triggers, 'hover', 'click']"
        :hideTriggers="triggers => [...triggers, 'click']"
        :skidding="-40"
    >
        <img :src="avatarSrc" class="avatar" />
        <template #popper>
            <div>Nothing special</div>
        </template>
    </VMenu>
</template>

<script>
import { Menu as VMenu } from 'floating-vue';
import "floating-vue/dist/style.css";
export default {
    components: {
        VMenu
    }
}
</script>
```

Happening every where:
![image](https://user-images.githubusercontent.com/49343539/161431507-e978edd2-4755-439b-8702-2b4206b210e2.png)

Plus
I'm using bootstrap 5 style sheet from global import

Help
Is it only me has this issue?

**Comment by Akryum** [comment]
This is due to improved a11y of floating-vue. What you are seeing is the focus outline rendered by the browser.

```css
.v-popper__popper {
  outline: none;
}
```

**Comment by AlotOfBlahaj** [comment]
same question.
Thank you

> This is due to improved a11y of floating-vue. What you are seeing is the focus outline rendered by the browser (浏览器) . To remove it:
> 
> ```css
> .v-popper__popper {
>   outline: none;
> }
> ```
