### ISSUE TITLE
v-tooltip is stuck if mouse moves through it

### ISSUE THREAD

**Issue by enodr** [Akryum/floating-vue#851]
Hi,

I have a strange behavior with v-tooltips being stuck (will not disappear) but only when the mouse moves over the content of the tooltip. It there a configuration to avoid this?

Example: tooltip appears when hovering the icon and is stuck if I move the mouse on the right passing through the tooltip content (my mouse pointer being on the right of the Kibana tooltip now)

![image](https://user-images.githubusercontent.com/10436257/162031401-6d6b2d1f-4f71-40a6-b66a-492926dead48.png)

Thanks

**Comment by Akryum** [comment]
Try `popperHideTriggers: ['hover']` ([docs](https://floating-vue.starpad.dev/api/#popperhidetriggers))

**Comment by enodr** [comment]
Thanks for the tip.

It does fixe the issue, even though I don't understand why the problem doesn't exists in the samples I saw. Anyway in main.js I have set this line as a solution:

`FloatingVue.options.popperHideTriggers = ['hover'];`

**Comment by Zedicius** [comment]
I'm having the same issue, but this started happening only recently.  Was there an update?

**Comment by Zedicius** [comment]
Welp, I fixed it by using the component tooltip instead of the directive so I could use the hide() function on mouseLeave.  Too bad this makes the directives almost useless though.

**Comment by Akryum** [comment]
You can do `FloatingVue.options.themes.tooltip.popperHideTriggers = ['hover']` to only apply to tooltips

**Comment by Akryum** [comment]
@Zedicius see my comment above to apply the workaround to all tooltips

**Comment by Akryum** [comment]
You don't need the workaround as of 1.0.0-beta.16 and 2.0.0-beta.14
