### ISSUE TITLE
Where should I put my styling for the tooltips?

### ISSUE THREAD

**Issue by LovelyAndy** [Akryum/floating-vue#859]
So I have been trying to use this library a couple times and find the customization a bit hard to understand, so I apologize if this is spelled out somewhere where I have missed it. 

**v-tooltip usecase**
```
 <div v-tooltip="'View Comparison'">
          hover me!
</div>
```

**main.ts**
```
import FloatingVue from 'floating-vue'
import 'floating-vue/dist/style.css'

app.use(FloatingVue, {
  themes: {
    comparison: {
      $extend: 'tooltip',
      triggers: ['hover'],
      autoHide: true,
      placement: 'top',
    },
  },
})
app.mount('#app')
```

Then in my **global.sass** file, I've added the code from the theme editor:

```
.v-popper--theme-comparison .v-popper__inner
  background: #4056a0
  color: #ffffff
  padding: 12px
  border-radius: 8px

.v-popper--theme-comparison .v-popper__arrow-outer
  border-color: #4056a0
```

Nothing here seems to work and I really have been confused as to how I can properly update the tooltip to my own theme. 

Any advice would be greatly appreciated!

Thank you

**Comment by Akryum** [comment]
Maybe a specificity issue?

**Comment by LovelyAndy** [comment]
> Maybe a CSS specificity issue?

The trouble with specificity is I'm not sure what I can target. Inspecting the DOM only shows the `v-popper--has-tooltip` class. Styling this changes the slotted content, not the tooltip itself. I apologize if I'm looking in the wrong spot, but what exactly do I target if just trying to change the background color of the `v-tooltip`? Simply styling `v-tooltip` doesn't really work and I don't even think I need to mess with themes or anything; I just need the background to be blue and the text white.

Thank you for your quick responses so far!

**Comment by LovelyAndy** [comment]
For anyone looking at this, this worked for me
```
.v-popper__popper
  .v-popper__wrapper
    .v-popper__inner
      background-color: #4056a0
      color: #ffffff
      padding: 12px
      border-radius: 8px
```

**Comment by LovelyAndy** [comment]
> So it's a CSS specificity issue

Yes, I wasn't sure what I needed to target. Not sure why they weren't showing up in the devtools. 

Sorry for the spam comments here!

**Comment by Akryum** [comment]
The poppers are mounted on the `container` (by default it's the body). So look there and you will find the dom nodes related to your tooltips (you can use the source tab first to pause Javascript).

**Comment by Klodovsky** [comment]
Hi , I've been able to edit the tooltip style directly on the browser but when I tried to override those classes it's showing me that the inner selector has never been used : 
![image](https://user-images.githubusercontent.com/55706752/175125267-847af90f-eaff-4c4d-bd00-af511a745fca.png)

![image](https://user-images.githubusercontent.com/55706752/175125001-d417532a-92b5-4158-aa10-55b2654cf8f2.png)

any idea please @Akryum @LovelyAndy ?

**Comment by bcakmakoglu** [comment]
@Klodovsky 
`v-popper__backdrop` doesn't have any child elements with the class `v-popper__wrapper` so your selector doesn't work.

Try it like suggested in this thread
```css
.v-popper__popper
.v-popper__wrapper
.v-popper__inner {
	/* your styles */
}
```
