### ISSUE TITLE
v-tooltip: Unrecognized Vue directive

### ISSUE THREAD

**Issue by martinszeltins** [Akryum/floating-vue#863]
Everything works but I am seeing an error about `unrecognized vue directive` in my editor. I am using phpstorm as my editor. Do I need to add something extra for it to recognize this directive?

![image](https://user-images.githubusercontent.com/34019878/170656618-1b2cd11d-3c25-4343-a666-011db482fde6.png)

This is how I have it installed and set up: 

my **main.ts** file:

```js
import App from './App.vue'
import '@/assets/css/app.css'
import { createApp } from 'vue'
import FloatingVue from 'floating-vue'
import { registerGlobalComponents } from '@/services/globalComponentsService'
import { registerCustomDirectives } from '@/services/customDirectivesService'

const app = createApp(App)

registerGlobalComponents(app)
registerCustomDirectives(app)

app.use(FloatingVue)
   .mount('#app')

```

**UPDATE:**
This seems to be an issue with the way I was using the FloatingVue library. I installed it from a "shared" npm package and for some reason my IDE failed to recognize it.

**Comment by alexose** [comment]
There's something odd going on with the floating-vue npm entry.  Seems like the newest version available there is `2.0.0-beta.16`...

**Comment by Akryum** [comment]
floatinghvue is the newest code

**Comment by alexose** [comment]
I only see up to 2.0.0-beta.16 here: https://www.npmjs.com/package/floating-vue?activeTab=versions
Where as v-tooltip has all of the version 3 and version 4 code: https://www.npmjs.com/package/floating-vue?activeTab=versions

Am I misunderstanding?

**Comment by martinszeltins** [comment]
I updated the issue, it seems to be the problem with the way I was using FloatingVue. I have a shared project that I pulled in using npm and for some reason my IDE failed to recognize it.

**Comment by stichingsd-vitrion** [comment]
Any update on this?

**Comment by Muetze42** [comment]
No solution?

**Comment by inikoo** [comment]
hello any update on this?
