### ISSUE TITLE
How to stop VMenu from closing

### ISSUE THREAD

**Issue by NightCatSama** [Akryum/floating-vue#881]
When I type text in a pop-up window, it automatically closes when the mouse is over the input method. How do I fix this
![QQ20220728-235248-HD (1)](https://user-images.githubusercontent.com/13888962/181587890-85d344ec-8b8c-44dc-8af2-86e73c14c08c.gif)
?

**Comment by JorisBassle** [comment]
Hi, I just happen to see this while I was searching for an answer myself.

You can provide the property autoHide to the VMenu component and set it to false.
