### ISSUE TITLE
Crashes in ESM SSR: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by negezor** [Akryum/floating-vue#896]
`Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.`

Applying any of the above fixes the problem of my ESM SSR server crashing. I'm using a clean Vite build for SSR.

**Comment by leomp12** [comment]
Same problem here 🙃 
Output file should be `floating-vue.mjs` instead of `floating-vue.es.js`

**Comment by leomp12** [comment]
I'm importing respective src file for now `import VTooltip from 'floating-vue/src/directives/v-tooltip';`

**Comment by susnux** [comment]
I encountered the same problem and submitted a PR which will fix it: #935
