### ISSUE TITLE
Which is the latest version for Vue 3?

### ISSUE THREAD

**Issue by crystalfp** [Akryum/floating-vue#904]
I'm a little confused.
There is this version that said 2.3.1 but the npm package is 2.0.0-beta.20
In the [releases page](https://github.com/Akryum/floating-vue/releases) you find the 3.0.0-beta.1
There are two "last version" sites: https://floating-vue.starpad.dev/ and https://v-tooltip.netlify.app/ that are identical (I understand, the last is wip)
So, from where should I install the latest and greatest floating-vue version?
Thanks!

**Comment by Akryum** [comment]
=> `floating-vue`

**Comment by crystalfp** [comment]
Exactly this is the package I have installed, But the version of the package is "^2.0.0-beta.20"
This means that till 3.0.0 will be out this is the latest version available as an npm package?
Anyway, the package is very good and works well, so I hope to install soon a modern version.
Thanks!
mario

**Comment by Akryum** [comment]
There is no `floating-vue` v3 currently being worked on. It was the old `v-tooltip` package.
https://floating-vue.starpad.dev/migration/migration-from-v2.html
https://floating-vue.starpad.dev/migration/migration-from-v3.html

**Comment by Akryum** [comment]
See the up-to-date [changelog here](https://github.com/Akryum/floating-vue/blob/main/CHANGELOG.md).
