### ISSUE TITLE
noAutoFocus for Vue 2 project

### ISSUE THREAD

**Issue by Klumper** [Akryum/floating-vue#907]
Hi,

I am trying to use an input element as a trigger for the `<VDropdown />`  component. The input element loses focus whenever the popover opens. After some searching I found out a possible fix was released for the Vue 3 version.

Is it possible to release the changes from [this commit ](https://github.com/Akryum/floating-vue/commit/919df7c71c7c058e36be0e04121adbdc2a8939b9) to the `@vue2` tag?

**Comment by skjnldsv** [comment]
@Akryum can you update us please?
https://github.com/Akryum/floating-vue/pull/894

**Comment by Akryum** [comment]
Done

**Comment by skjnldsv** [comment]
You're awesome!
May both sides of your pillows always be cold and your bed warm and cozy! :bow: :pray:
