### ISSUE TITLE
cant change default disposeTimeout value 

### ISSUE THREAD

**Issue by Kristian383** [Akryum/floating-vue#941]
ive tried passing it as a string or as a number but it disappears (from what it looks based on the documentation) from dom only after 5s, and not for example after 1 second

![image](https://user-images.githubusercontent.com/48631826/226203102-b931ebcc-d3ac-42ce-a418-9085b3581083.png)

![image](https://user-images.githubusercontent.com/48631826/226202966-91d85cd7-3b2f-46e4-8110-d55625e71518.png)

**Comment by RAIbrahim360** [comment]
also not working in 1.0.0-beta.19 version. There's no disposeTimeout prop, either
