### ISSUE TITLE
Cannot get it to work with Vue 3

### ISSUE THREAD

**Issue by matthewknill** [Akryum/floating-vue#955]
I installed the package using the following:
```bash
npm i -S floating-vue@2.0.0-beta.20
```
I then created the following component:
```vue
<template>
    <VTooltip>
        <button>TEST</button>
        <template #popper>
            TEST TOOLTIP
        </template>
    </VTooltip>
</template>
<script setup>
import { VTooltip } from "floating-vue"
</script>
```

When I attempt to use this component, I get the following error:
![image](https://github.com/Akryum/floating-vue/assets/50228686/acce0497-576b-4463-849d-3128f5930ab5)

As per the doco, I also attempted to add `use(FloatingVue)` after importing with `import FloatingVue from 'floating-vue'` in my `main.ts` file but it produced the same error.

**Comment by or2e** [comment]
After upgrading to vue 3.3 (nuxt 3.5) there is an error (

![image](https://github.com/Akryum/floating-vue/assets/33551334/9f1d1d9d-51ea-4342-a4a8-af14d935d6a4)

<details>
<summary>envinfo</summary>

```
System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (16) x64 Intel(R) Core(TM) i9-9900KF CPU @ 3.60GHz
    Memory: 11.10 GB / 15.58 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  npmPackages:
    floating-vue: ^2.0.0-beta.20 => 2.0.0-beta.20 
    nuxt: ^3.5.0 => 3.5.0 
```
</details>

**Comment by or2e** [comment]
@matthewknill 
Try to reproduce here https://stackblitz.com/

**Comment by Joshw8** [comment]
You are importing the directive and using the component approach.

`import {Tooltip as VTooltip } from "floating-vue"`

**Comment by matthewknill** [comment]
Cheers @Joshw8 

Attempted to use `use(FloatingVue)` and it seems to work now.
