### ISSUE TITLE
Not working individually neither on docs site https://floating-vue.starpad.dev/

### ISSUE THREAD

**Issue by ealbinu** [Akryum/floating-vue#964]
Every tooltip appears on the top-left corner of the window.
Tested in Arc Mac, Chrome Mac, Safari Mac, Safari ios.

**Comment by BayBreezy** [comment]
Same here

**Comment by antfu** [comment]
The doc site should be fixed. It seems there is some breaking change between `v1.1.1` and `v1.2.0` of `@floating-ui/dom`. Need to investigate further
