### ISSUE TITLE
Beta 22 Nuxt module: nuxt undefined

### ISSUE THREAD

**Issue by joneath** [Akryum/floating-vue#968]
The nuxt module blows up on nuxt boot. From the src it looks like `this` is undefined on line 2 `const nuxt = this.nuxt`. Any reason not to use either `defineNuxtModule` (probably don't want to add `@nuxt/kit` as a dependency) or use the passed `nuxt` instance as described in the [docs](https://nuxt.com/docs/guide/going-further/modules)? 

`Cannot read properties of undefined (reading 'nuxt')`

**Comment by orlanrepo** [comment]
Didn't go into the details but I had the same problem when adding the `float-vue/nuxt` to `modules` in `nuxt.config.ts`.

I created my own plugin:

`/plugins/floating-vue.ts`
contents:
`
import { defineNuxtPlugin } from "#app";
import FloatingVue from "floating-vue";
import "floating-vue/dist/style.css";

export default defineNuxtPlugin((nuxtApp) => {
  // @TODO cutomization
  nuxtApp.vueApp.use(FloatingVue);
});

`

and floating-vue works in nuxt 3.5.3.

**Comment by joneath** [comment]
> Didn't go into the details but I had the same problem when adding the `float-vue/nuxt` to `modules` in `nuxt.config.ts`.
> 
> I created my own plugin (a temp solution) :
> 
> `/plugins/floating-vue.ts` contents:
> 
> ```
> import { defineNuxtPlugin } from "#app";
> import FloatingVue from "floating-vue";
> import "floating-vue/dist/style.css";
> 
> export default defineNuxtPlugin((nuxtApp) => {
>   // @TODO cutomization
>   nuxtApp.vueApp.use(FloatingVue);
> });
> ```
> 
> and floating-vue works in nuxt 3.5.3.

This was the documented solution to using the package in Nuxt prior to beta 21 when supposedly a in package nuxt module was added. Beta 22 added the module but in a broken state 😔

**Comment by madroot** [comment]
> Не вдавался в подробности, но у меня была такая же проблема при добавлении `float-vue/nuxt` в `modules` `nuxt.config.ts`.
> 
> Я создал свой собственный плагин (временное решение) :
> 
> `/plugins/floating-vue.ts` Содержание:
> 
> ```
> import { defineNuxtPlugin } from "#app";
> import FloatingVue from "floating-vue";
> import "floating-vue/dist/style.css";
> 
> export default defineNuxtPlugin((nuxtApp) => {
>   // @TODO cutomization
>   nuxtApp.vueApp.use(FloatingVue);
> });
> ```
> 
> и floating-vue работает в nuxt 3.5.3.

[Vue warn]: Failed to resolve component: VTooltip                                                                                                                                                                             21:07:50
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[Vue warn]: Non-function value encountered for default slot. Prefer function slots for better performance.                                                                                                                    21:07:50
[Vue warn]: Component <Anonymous> is missing template or render function.     

> Didn't go into the details but I had the same problem when adding the `float-vue/nuxt` to `modules` in `nuxt.config.ts`.
> 
> I created my own plugin (a temp solution) :
> 
> `/plugins/floating-vue.ts` contents:
> 
> ```
> import { defineNuxtPlugin } from "#app";
> import FloatingVue from "floating-vue";
> import "floating-vue/dist/style.css";
> 
> export default defineNuxtPlugin((nuxtApp) => {
>   // @TODO cutomization
>   nuxtApp.vueApp.use(FloatingVue);
> });
> ```
> 
> and floating-vue works in nuxt 3.5.3.

I did so, but when using the error: (nuxt 3.5.2, "floating-vue": "^2.0.0-beta.22")

[Vue warn]: Failed to resolve component: VTooltip                                                                                                                                                                             21:07:50
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[Vue warn]: Non-function value encountered for default slot. Prefer function slots for better performance.                                                                                                                    21:07:50
[Vue warn]: Component <Anonymous> is missing template or render function.
