### ISSUE TITLE
It doesn't work with Vue 3/Vite

### ISSUE THREAD

**Issue by Dagge11** [Akryum/floating-vue#971]
This doesn't work. I have installed it and enabled globally with
```
import FloatingVue from 'floating-vue';
createApp(App).use(router).use(FloatingVue).mount('#app');
```
And I have used it inside a component as a directive` v-tooltip="'Hello there'" `and it doesn't work

**Comment by antfu** [comment]
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)
