### ISSUE TITLE
Request: should have an option to remove the arrow

### ISSUE THREAD

**Issue by timothymarois** [Akryum/floating-vue#978]
Should have a way to remove the arrow since that is a design choice. Maybe there is; maybe you can use CSS for it. But there should be a config to remove it. Having the arrow dictates the component's visual, therefore, limits its use.

**Comment by timothymarois** [comment]
Reopening because its still relevant. You can do 

```
<style>
.v-popper--theme-dropdown-menu .v-popper__arrow-container {
    display: none;
}
</style>
```

however, this is a hack, and should have a real solution within the config.

**Comment by antfu** [comment]
I don't think it's a hack, it's a valid CSS override. This is needed when you are **using the default theme**, while you can always write your own theme without arrows or whatever you want. Floating Vue itself is styleless.

**Comment by pastukhvladyslav** [comment]
The CSS worked great, but it applies changes accross the whole app. Is there a way to hide arrow only for some usages?
