### ISSUE TITLE
VDropdown unit testing with vue-test-utils

### ISSUE THREAD

**Issue by dirago** [Akryum/floating-vue#996]
Hello all 👋

I'm struggling a lot with unit testing `VDropdown`, I can't access what's inside <template #popper> when I trigger a `click` on the dropdown trigger.

My dependencies:

- `"vue": "^3.3.7"`
- `"@vue/test-utils": "^2.4.1"`
- `"floating-vue": "^2.0.0-beta.24"`
- `"vitest": "^0.34.6"`

Here's a simple example where my test fails:

> NavBar.vue
```vue
<template>
  <div class="nav-bar">
    <VDropdown
      data-test="nav-bar.dropdown"
      :distance="12"
      no-auto-focus
      placement="top-start"
      skidding="-6"
    >
      <div data-test="nav-bar.navigation-trigger">
      ...
      </div>
      
      <template #popper="{ hide }"> // I don't use v-close-popper since it does not always work
        <ul data-test="nav-bar.navigation-dropdown" @click="hide">
          ...
        </ul>
      </template>
    </VDropdown>
  </div>
</template>
``` 

> NavBar.spec.ts
```ts
import NavBar from '@/ui/components/nav-bar/NavBar.vue';
import { mount } from '@vue/test-utils';
import { Dropdown } from 'floating-vue';

describe('NavBar', () => {
  it('should display dropdown when trigger is clicked', async () => {
    expect.assertions(1)
    const wrapper = mount(NavBar, {
      global: {
        stubs: {
          VDropdown: Dropdown
        }
      }
    });
    
    await wrapper.find('[data-test="nav-bar.navigation-trigger"]').trigger('click');
    // fails also with `await wrapper.vm.$nextTick()`
    // fails also with `await nextTick()`
    
    expect(wrapper.find('[data-test="nav-bar.navigation-dropdown"]').exists()).toBeTruthy(); // fails
  });
});
```

> main.ts

```ts
...
const app = createApp(App);
app.component('VDropdown', Dropdown);
...
```

Has anybody faced this? Do you have any working solution? 🙏

**Comment by dirago** [comment]
Nobody?

**Comment by ItMaga** [comment]
Hi @dirago!

I'm not sure, because I didn't test it. But I would suggest checking the content not inside the wrapper but in `document.body` for the reason of appending the popper to the body. And you should use utility `waitFor`.

**Comment by dirago** [comment]
> @dirago have you found a solution?

not yet...

**Comment by jjaramillom** [comment]
@dirago @Dino-Kupinic I'm also struggling with this and haven't been able to find a solution. Could any of you make it work?

**Comment by Dino-Kupinic** [comment]
> @dirago @Dino-Kupinic I'm also struggling with this and haven't been able to find a solution. Could any of you make it work?

Sadly no, would be nice if testing was included in the docs

**Comment by byv55f5f5** [comment]
I also face this problem too. It was fine when I used v-tooltip v2.

**Comment by dirago** [comment]
> I also face this problem too. It was fine when I used v-tooltip v2.

I guess we're all using v-tooltip v2 (renamed to floating-vue), can you share some code to understand how you figured it out?

**Comment by byv55f5f5** [comment]
> > I also face this problem too. It was fine when I used v-tooltip v2.
> 
> 
> 
> I guess we're all using v-tooltip v2 (renamed to floating-vue), can you share some code to understand how you figured it out?

I mean the old version was fine. After I upgrade v-tooltip to floating-vue, all of my unit-test related to floating-vue are broken too. The test-utils can not find the element in popper after click event is triggered.

**Comment by Akryum** [comment]
Content inside the `#popper` slot will be rendered on `body` by default, so it might explain why you can't access it through `wrapper`.

**Comment by Dino-Kupinic** [comment]
> Content inside the `#popper` slot will be rendered on `body` by default, so it might explain why you can't access it through `wrapper`.

yes. How should we go about testing then?

**Comment by dirago** [comment]
Still no satisfactory result, here's my test:

```ts
import NavBar from '@/ui/components/nav-bar/NavBar.vue';
import { mount } from '@vue/test-utils';
import { Dropdown } from 'floating-vue';

describe('NavBar', () => {
  it('should display dropdown when trigger is clicked', async () => {
    expect.assertions(1);
    const wrapper = mount(NavBar, {
      attachTo: document.body,
      global: {
        stubs: {
          VDropdown: Dropdown
        }
      }
  })

    await wrapper.find('[data-test="nav-bar.navigation-trigger"]').trigger('click');
    console.log(document.documentElement.innerHTML); // see below

    expect(document.querySelector('[data-test="nav-bar.navigation-dropdown"]')).not.toBeNull(); // fails
    wrapper.unmount(); // obligatory if you do not want to pollute your next unit tests
  });
});
```

Here's what @vue/test-utils renders with `attachTo` (before AND after clicking the trigger)

```html
<head></head>
<body>
  <div data-v-app="">
    <div class="nav-bar" data-test="nav-bar">
      <div class="v-popper v-popper--theme-dropdown" data-test="nav-bar.dropdown">
        <div class="nav-bar-element nav-bar-element-nav text-13-medium" data-test="nav-bar.navigation-trigger">
          I am the trigger
        </div>
      </div>
    </div>
  </div>
</body>
```

You can notice <body> don't have the class `v-popper--some-open` and the dropdown content is not rendered.

I'm going to give up for now, I'm probably missing something but I've already spent way too much time on this. The problem could come from `@vue/test-utils` or `happy-dom` (I didn't test with `jsdom` and it will break all my UT)

**Comment by Akryum** [comment]
Maybe you can stub the dropdown component to test the popper content?

**Comment by NeoLSN** [comment]
Need to install `floating-vue` as a plugin, but still don't have a good way to trigger it in test case.

```typescript
import NavBar from '@/ui/components/nav-bar/NavBar.vue';
import { config, mount } from '@vue/test-utils';
import FloatingVue from 'floating-vue';

describe('NavBar', () => {
  beforeAll(() => {
    config.plugins.VueWrapper.install(FloatingVue);
  });

  it('should display dropdown when trigger is clicked', async () => {
    expect.assertions(1);
    const wrapper = mount(NavBar, {
      attachTo: document.body,
    })

    await wrapper.find('[data-test="nav-bar.navigation-trigger"]').trigger('click');
    console.log(document.documentElement.innerHTML); // see below

    expect(document.querySelector('[data-test="nav-bar.navigation-dropdown"]')).not.toBeNull(); // fails
    wrapper.unmount(); // obligatory if you do not want to pollute your next unit tests
  });
});
```

**Comment by dirago** [comment]
@Akryum VDropdown is already stubbed in `mount`, isn't it?

```ts
import { Dropdown } from 'floating-vue';

const wrapper = mount(NavBar, {
    attachTo: document.body,
    global: {
        stubs: {
            VDropdown: Dropdown
        }
    }
})
```

@NeoLSN why do you want to install floating-vue since we stub Dropdown? Maybe I miss something but I might only want to use Dropdown and instantiate it in `main.ts` with:

```ts
import { Dropdown } from 'floating-vue';

app.component('VDropdown', Dropdown);
```

**Comment by NeoLSN** [comment]
I used this [solution](https://github.com/Akryum/floating-vue/issues/996#issuecomment-1891856841) before, but it's not working for me.

**Comment by Akryum** [comment]
By stubbing I mean stubbing using a dummy component with a popper slot

**Comment by dirago** [comment]
@Akryum oh ok, I would have preferred it to work without having to stub it all but let's try

edit: ok it works with:

```ts
const VDropdownStub = defineComponent({
  setup() {
    const showPopper = ref(false);

    return { showPopper };
  },
  template: `
    <div>
      <div @click="showPopper = !showPopper">
        <slot></slot>
      </div>
      <div v-if="showPopper">
        <slot name="popper"></slot>
      </div>
    </div>
  `,
});

config.global = {
  stubs: {
    VDropdown: VDropdownStub,
  },
};
```

I decided to put this on the global config but you can also do the same in `mount` @NeoLSN @jjaramillom @Dino-Kupinic @byv55f5f5

**Comment by jjaramillom** [comment]
@dirago Working like a charm. Thanks a lot for the snippet pal.
